# https://github.com/knojector/SteamAuthenticationBundle for configuration documentation
knojector_steam_authentication:
    api_key: "%env(STEAM_API_KEY)%"
    login_route: ''
    login_redirect: ''
    user_class: ''
